myss SEGMENT PARA STACK 'STCK'
	DW 20 DUP(?)
myss ENDS

myds SEGMENT PARA 'VERI'
SAYI1	DD 0FFFFFFFFH
SAYI2	DD 0FFFFFFFFH
SONUC   DQ 0H
myds ENDS

mycs SEGMENT PARA 'KOD' 
	ASSUME CS:mycs,DS:myds,SS:myss
ANA	PROC FAR 
		PUSH DS
		XOR AX,AX
		PUSH AX
		
		MOV AX,myds
		MOV DS,AX
		
		XOR DX,DX
		MOV BX,WORD PTR [SAYI1]
		MOV AX,WORD PTR [SAYI2]
		MUL BX
		MOV WORD PTR [SONUC],AX
		MOV WORD PTR [SONUC+2],DX
		
		XOR DX,DX
		MOV AX,WORD PTR [SAYI2+2]
		MUL BX
		ADD WORD PTR [SONUC+2],AX
		ADC WORD PTR [SONUC+4],0
		ADD WORD PTR [SONUC+4],DX
		ADC WORD PTR [SONUC+6],0
		
		XOR DX,DX
		MOV BX,WORD PTR [SAYI1+2]
		MOV AX,WORD PTR [SAYI2]
		MUL BX
		ADD WORD PTR [SONUC+2],AX
		ADC WORD PTR [SONUC+4],0
		ADD WORD PTR [SONUC+4],DX
		ADC WORD PTR [SONUC+6],0

		XOR DX,DX
		MOV BX,WORD PTR [SAYI1+2]
		MOV AX,WORD PTR [SAYI2+2]
		MUL BX 
		ADD WORD PTR [SONUC+4],AX
		ADC WORD PTR [SONUC+6],0
		ADD WORD PTR [SONUC+6],DX	
	

	
	RETF
ANA	ENDP
mycs	ENDS
	END ANA