PAGE 60,80
TITLE ORNEK
EXTRN YARD:FAR  
PUBLIC SAYI1,SAYI2,SONUC
STACKSG SEGMENT PARA STACK 'STACK'
	DW 32 DUP(?)
STACKSG ENDS

DATASG SEGMENT PARA PUBLIC 'DATA'
		SAYI1 DW 10
		SAYI2 DW 99
		SONUC DQ 0
DATASG ENDS

CODESG SEGMENT PARA 'CODE'

			ASSUME CS:CODESG,DS:DATASG,SS:STACKSG
BASLA PROC FAR
		PUSH DS
		XOR AX,AX
		PUSH AX
		
		MOV AX,DATASG
		MOV DS,AX
		
		CALL YARD

		RETF
BASLA ENDP 	
CODESG ENDS
END BASLA
		