PAGE 60,80
TITLE BINARY SEARCH

STACKSG SEGMENT PARA STACK 'STACK'
	DW 20 DUP(?)
STACKSG ENDS

DATASG SEGMENT PARA 'DATA'
	DIZI       DB 0,1,2,3,5,7,8,11,15,25
	BUYUKINDIS DB 10
	KUCUKINDIS DB -1
	ARANAN 	   DB 16
	

DATASG ENDS

CODESG SEGMENT PARA 'CODE'
			ASSUME CS:CODESG,SS:STACKSG,DS:DATASG
			
	BASLA PROC FAR 
		PUSH DS
		XOR AX,AX
		PUSH AX
		
		MOV AX,DATASG
		MOV DS,AX
		
		XOR SI,SI
		
		;WHİLE KULLANARAK YAPIYORUM.
		
L1:		
		MOV AL,BUYUKINDIS
		DEC AL
		CMP AL,KUCUKINDIS
		JG CONTINUE
		MOV AX,1111H  ;BULUNMADIYSA AX E 1111 YAZDIRIYORUM.
		JMP SON
CONTINUE:		
		XOR AX,AX
		MOV AL,BUYUKINDIS
		ADD AL,KUCUKINDIS
		MOV CX,2
		DIV CX
		XOR AH,AH  ;SI YA ATARKEN AH DA DEGISIK DEGERLER OLUSUYOR.
		MOV SI,AX
		
		MOV BL,ARANAN
		CMP DIZI[SI],BL
		JNZ NFOUND
		MOV AX,2222H  ;BULUNDUYSA AX E 2222 YAZDIRIYORUM.
		JMP SON

NFOUND: CMP DIZI[SI],BL
		JL BIDEGIS			;EGER DIZIDEKI DEGER ARADIGIM DEGERDEN KUCUKSE KUCUKINDIS I DEGISTIRIYORUM
		MOV CX,SI			;BUYUK ISE BUYUK INDISI DEGISTIRIYORUM.
		MOV BUYUKINDIS,CL
		JMP L1
BIDEGIS:MOV CX,SI
		MOV KUCUKINDIS,CL
		JMP L1	
		
SON : 
			
		
RETF 
BASLA ENDP
CODESG ENDS
END BASLA
		