STACKSG SEGMENT PARA STACKSG 'STACK'
		DW 20 DUP(?)
STACKSG ENDS

DATASG SEGMENT PARA 'DATA'
		TEKTOP 		DD 0
		CIFTTOP		DD 0
		TEKSAY		DW 0
		CIFTSAY 	DW 0
		TEKORT		DW 0	
		CIFTORT		DW 0
		DIZI 		DW 300 DUP(?)
		ELEMAN		DW 300
DATASG ENDS

CODESG SEGMENT PARA 'CODE'

				ASSUME CS:CODESG,DS:DATASG,SS:STACKSG
				
BASLA PROC FAR
			PUSH DS 
			XOR AX,AX
			PUSH AX
			
			MOV AX,DATASG
			MOV DS,AX
			
			MOV CX,ELEMAN
			XOR SI,SI
			
LABEL1:		MOV AX,DIZI[SI]	
			TEST AX,0001H
			JZ CIFTLABEL
			INC TEKSAY
			ADD WORD PTR [TEKTOP],AX
			ADC WORD PTR [TEKTOP+2],0
			
			JMP ARTIR
CIFTLABEL:	INC CIFTSAY
			ADD WORD PTR [CIFTTOP],AX
			ADC WORD PTR [CIFTTOP+2],0
			
ARTIR:		ADD SI,2
			LOOP LABEL1
			
			MOV DX,WORD PTR [CIFTTOP+2]
			MOV AX,WORD PTR [CIFTTOP]
			DIV CIFTSAY
			MOV CIFTORT,AX
			MOV DX,WORD PTR [TEKTOP+2]
			MOV AX,WORD PTR [TEKTOP]
			DIV TEKSAY
			MOV TEKORT,AX
			
			RETF 
	BASLA ENDP
CODESG ENDS
END BASLA	
			
			
			
			
			