PAGE 60,80
TITLE OGRENCI NOTORTALAMALARI ALAN PROG.

STACKSG SEGMENT PARA STACK 'STACK'
	DW 20 DUP(?)
STACKSG ENDS

DATASG SEGMENT PARA 'DATA'
	TOPLAM 		DW 0
	ORTALAMA	DB 0
	OGRENCIVAL 	DW 0
	OGRNOT      DB 	5 DUP(?)		;ORNEK SAYILAR VERILDI. NORMALDE 120 OGRENCI
	NOTDIZI	    DB  20,25,15,32 DUP(50)	;840 TANE NOT 
	KALAN 		DB 0			
	OGRENCISAY  DB 5				;120 OGRENCI	
	BITTI 		DB "ISLEM SONA ERDI $"
	SABIT 		DW 0

DATASG ENDS

CODESG SEGMENT PARA 'CODE'
	ASSUME CS:CODESG,DS:DATASG,SS:STACKSG
	
	BASLA PROC FAR 
		PUSH DS
		XOR AX,AX
		PUSH AX
		
		MOV AX,DATASG
		MOV DS,AX
		
		XOR SI,SI
		XOR DI,DI
		MOV CX,5			;OGRENCI SAYISI ATANDI
		
L1:		
		XOR SI,SI
		MOV OGRENCIVAL,0	;OGRENCIVAL DEGISKENI OGRENCININ  ODEVLERDE ALDIGI TOPLAM NOTLARI TUTMAKTADIR.	
		PUSH CX
		PUSH DI
		MOV CX,7			;ODEV SAYISI ATANDI
L2:		
		XOR AX,AX
		
		MOV AL,5
		MUL SI
		ADD AX,SABIT		;SABIT DEGERI HER OGRENCI ICIN 1 ARTIYOR.ORNEGIN ILK TUR ICIN BIRINCI OGRENCIYI DUSUNELIM.0*5+0 =0 YANI SIFIRINCI ELEMANI ALACAK
		MOV DI,AX			;IKINCI TUR ICIN 1*5+0 =5 DEGERINI ALACAK FAKAT BURDA DEGISEN DI REGISTERI.SABITIMIZ 0 KALDI IKINCI OGRENCIYE GECINCE SABITIMIZ 1 OLACAK
							;ORNEGIN 0*5+1=1  1*5+1=6  GORULDUGU GIBI 7 ODEV VERILDIGINDE 1. 6. VSVS DEGERLER 2.OGRENCIYE AIT OLUYOR. 
							;SON OLARAK BİR ÖRNEK DAHA VEREYİM 4. ÖĞRENCİ İÇİN 0*5+3=3 1*5+3=8 VS YANİ 3.DEGER 8. DEGER VSVS 4.ÖĞRENCİYE AIT OLACAK.
		XOR AX,AX
		
		MOV AL,NOTDIZI[DI]
		CBW 				;NOT DIZIM BYTE OLDUGU ICIN WORD TIPINE DONUSTURUYORUM.
		ADD OGRENCIVAL,AX	
		
		INC SI
		LOOP L2

		
		POP DI
		POP CX 
		XOR AX,AX
		MOV AX,OGRENCIVAL
		MOV BX,7			;BX DEGERINI SADECE 7 YE BOLMEK ICIN KULLANDIM. HER OGRENCININ KENDI ORTALAMASI BULMAK ICIN YAPILDI.								
		DIV BX			
		
		ADD TOPLAM,AX		;TOPLAM DEGISKENI OGRENCI ORTALAMASINI HESAPLAMAK ICIN TUTUKLU VE OGRENCI SAYISINA BOLUNDU.
		MOV OGRNOT[DI],AL
		
		INC DI 
		INC SABIT
		LOOP L1
		
		
		XOR AX,AX
		XOR DX,DX
		MOV AX,TOPLAM
		DIV OGRENCISAY	;TOPLAM OGRENCI SAYISINA BOLUNDU.
		
		MOV ORTALAMA,AL
		
		XOR SI,SI
		MOV CL,OGRENCISAY   ;OGRENCI SAYIM BYTE OLDUGU ICIN CX'E ATAMADIM.
		
L3:		
		XOR AX,AX
		MOV AL,OGRNOT[SI]
		CMP AL,ORTALAMA			;KALANLARI BULMAK ICIN SON DONGUM.
		JNB KALMADI
		INC KALAN
		
KALMADI:INC SI
		LOOP L3
			
		XOR AX,AX		;PROGRAMI DURDURMAK ICIN YAPILDI.
		MOV AH,09H
		LEA DX,BITTI
		INT 21H
		
		
		
	RETF 
BASLA ENDP
CODESG ENDS
END BASLA	