DATASG SEGMENT PARA 'DATA'
	 NOTLAR 	DB 280 DUP(?)
	 OGRSAY 	DW 280
	 KALAN 		DW 0
	 BUT 		DW 0
	 BASARILI 	DW 0
	 TOPNOT		DW 0
	 ESIK		DB 40
DATASG ENDS

STACKSG SEGMENT PARA STACK 'STACK'
		DW 20 DUP(?)
STACKSG ENDS

CODESG SEGMENT PARA 'CODE'
			ASSUME CS:CODESG,SS:STACKSG,DS:DATASG
			
BASLA PROC FAR 

			PUSH DS
			XOR AX,AX
			PUSH AX
			
			MOV AX,DATASG
			MOV DS,AX
			
			XOR SI,SI
			MOV CX,OGRSAY
		
LABEL1:	 	MOV AL,NOTLAR[SI]
			CMP AL,ESIK
			JAE ESIKUSTU
			INC KALAN
			JMP LABEL2
ESIKUSTU :	CBW
			ADD TOPNOT,AX
LABEL2:		INC SI
			LOOP LABEL1
			MOV CX,OGRSAY
			SUB CX,KALAN
			XOR DX,DX
			MOV AX,TOPNOT
			DIV CX
			XOR SI,SI
			MOV CX,OGRSAY
L2:			MOV AH,NOTLAR[SI]
			CMP AL,AH
			JBE GECTI
			CMP AH,ESIK
			JB  KALDI
			INC BUT
			JMP KALDI
GECTI:		INC BASARILI
KALDI:		INC SI
			LOOP L2
			RETF
	BASLA ENDP
CODESG ENDS
END BASLA
	
	
			
			
			
			
			