PAGE 60,80
TITLE YARDIMCI YORDAM

PUBLIC TOPLAMA

CODESG SEGMENT PARA 'CODE'
	ASSUME CS:CODESG
	
TOPLAMA PROC FAR 
	
	XOR AX,AX
	ADD AL,BL
	ADD AH,BH
	ADC AH,0
	RETF 
TOPLAMA ENDP
CODESG ENDS
END ;COK ONEMLI BURDAKI END DEN SONRA HICBIR SEY KONMAZ!
