PAGE 60,80
TITLE 32BIT SUM COM TIPI

CODESG SEGMENT PARA 'CODE'
	ORG 100H
ASSUME CS:CODESG,SS:CODESG,DS:CODESG,ES:CODESG

BILGI : JMP BASLA

SAYI1 	DD 0FFFFFFFFH
SAYI2 	DD 0FFFFFFFFH
TOPLAM 	DQ 0

BASLA PROC NEAR 

		XOR DX,DX
		
		MOV AX,WORD PTR[SAYI1]
		MOV BX,WORD PTR[SAYI2]
		ADD AX,BX
		ADC WORD PTR[TOPLAM+2],0
		ADD WORD PTR[TOPLAM],AX
		
		
		MOV AX,WORD PTR[SAYI1+2]
		MOV BX,WORD PTR[SAYI2+2]
		ADD AX,BX
		ADC WORD PTR [TOPLAM+4],0
		ADD WORD PTR [TOPLAM+2],AX
		ADC WORD PTR [TOPLAM+4],0
	
	RET 
	BASLA ENDP
	CODESG ENDS
	END BILGI
