	PAGE 60,80
	TITLE EN BUYUK ELEMAN BULUNMASI /COM TIPI
	
	CODESG SEGMENT PARA 'CODE'
	ORG 100H
	ASSUME CS:CODESG,SS:CODESG,DS:CODESG,ES:CODESG
	
BASLA : JMP MAXI

	ELEMAN DW 10
	DIZI   DW -4,23,456,4,8,67,-78,9,-99,256
	BUYUKSAY DW ?
	
MAXI PROC NEAR 

			MOV CX,ELEMAN
			LEA SI,DIZI
			DEC CX    		;ELEMAN SAYISINDAN BİR TANE EKSİK İŞLEM YAP
			MOV AX,[SI]
	
CEVRİM:		ADD SI,2
			CMP AX,[SI]
			JG 	DEVAM
			MOV AX,[SI]
DEVAM :		LOOP CEVRİM
			MOV BUYUKSAY,AX
			
			RET 
MAXI ENDP 
CODESG ENDS
		END BASLA 
		
			