PAGE 60,80
TITLE FREKANS COM TIPI

CODESG SEGMENT PARA 'CODE'
	ORG 100H
	ASSUME SS:CODESG,DS:CODESG,CS:CODESG,ES:CODESG
	
BILGI : JMP BASLA
		DIZI 	DW 10,2,5,6,7,9,1,0,3,4
		ELEMAN 	DW 10
		SONUC 	DW 11 DUP(0)

BASLA PROC NEAR

			XOR SI,SI
			XOR DI,DI
			MOV CX,ELEMAN
			LEA SI,DIZI
L1:					
			MOV DI,WORD PTR [SI]
			SHL DI,1
			DEC DI
			INC SONUC[DI]
			ADD SI,2
			LOOP L1

			
RET 
BASLA ENDP 
CODESG ENDS
END BILGI			