PAGE 60,80 
TITLE EKRANA MESAJ YAZDIRMA HARICI MACROILE

INCLUDE macrolar.mac

CODESG SEGMENT PARA 'CODE'
	ORG 100H
	ASSUME CS:CODESG,DS:CODESG,SS:CODESG,ES:CODESG
	
	
BASLA PROC NEAR
	
	SIL
	YAZDIR MESAJ
	RET
BASLA ENDP

MESAJ DB 'MACROLAR macrolar.mac DOSYASINDAN ALINDI $'

CODESG ENDS
END BASLA 