PAGE 60,80
TITLE OGRENCI NOT ORTALAMASI COM TIPI

CODESG SEGMENT PARA 'CODE'
	ORG 100H
	ASSUME CS:CODESG,DS:CODESG,SS:CODESG,ES:CODESG
BILGI : JMP BASLA
NOTLAR DB 100,50,24,11,99,295 DUP (66)
ELEMAN DW 300
ORT DB 0

BASLA PROC NEAR

		LEA SI,NOTLAR
		MOV CX,ELEMAN
		XOR AX,AX
		XOR DX,DX
L1:		
		ADD AL,[SI]
		ADC AH,0
		INC SI
		LOOP L1
		
		DIV ELEMAN
		MOV ORT,AL
		
		RET 
		BASLA ENDP
		CODESG ENDS
		END BILGI
	