PAGE 60,80
TITLE EKRANA YAZDIRMA COM TIPI 

CODESG SEGMENT PARA 'CODE'
	ORG 100H
	ASSUME CS:CODESG,DS:CODESG,SS:CODESG,ES:CODESG
	
YAZDIR PROC NEAR 
		LEA DX,MESAJ
		MOV AH,09H
		INT 21H
		RET
YAZDIR ENDP

MESAJ DB 'ASAF PAŞA ÇOK YAŞA!!!','$'
CODESG ENDS
END YAZDIR
		