PAGE 60,80
TITLE ISARETLI SAYILAR 

CODESG SEGMENT PARA 'CODE'
 ORG 100H 
 ASSUME CS:CODESG,SS:CODESG,DS:CODESG
 
 BILGI: JMP BASLA
 KENAR1 DB 1
 KENAR2 DB 12		
 KENAR3 DB 12
 
 BASLA PROC NEAR 
 
		XOR AX,AX

			 MOV AL,KENAR1
			 MOV AH,KENAR2
			 CMP AL,AH
			 JNZ ESKENARSIZ
			 MOV AH,KENAR3
			 CMP AL,AH
			 JNZ IKIZKENAR		
			 MOV DI,1
			 JMP SON	
IKIZKENAR:  MOV DI,2		
			JMP SON		
								
ESKENARSIZ:     XOR AX,AX
				MOV AL,KENAR1
				MOV AH,KENAR3
				CMP AL,AH
				JNZ CESITKONTROL		;EGER ESKENAR ISE DI=1
				MOV DI,2				;IKIZKENAR ISE 	  DI=2
				JMP SON					;CESITKENAR ISE   DI=3  GELMESINI ISTIYORUM.
CESITKONTROL:			
				MOV AL,KENAR2
				CMP AL,AH
				JNZ CESITKENAR
				MOV DI,2
				JMP SON
CESITKENAR:     MOV DI,3
						
 SON :
				XOR AX,AX ;OYLESINE
				XOR BX,BX
 RET
 BASLA ENDP
 CODESG ENDS
 END BILGI